cargo-features = ["codegen-backend"]

[package]
name = "engine_4"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy_math = "0.17.2"
bumpalo = { version = "3.19.0", features = ["collections"] }
color-eyre = "0.6.5"
egui_glium = "0.31.1"
egui_plot = {version = "0.31", optional = true}
env_logger = "0.11.8"
fontdue = "0.9.3"
fps_ticker = "1.0.0"
glium = "0.36.0"
glyph_brush = "0.7.12"
image = "0.25.8"
include_folder = "0.3.0"
log = "0.4.28"
lyon = "1.0.16"
nalgebra = { version = "0.34.1", features = ["convert-glam030"] }
obj-rs = "0.7.4"
palette = "0.7.6"
paste = "1.0.15"
rand = "0.9.2"
rapier2d = { version = "0.30.1", features = ["simd-stable"] }
tunes = { version = "1.0.2", features = ["gpu"] }
winit_input_helper = "0.17.0"
engine_4_macros = { path = "./crates/engine_4_macros" }

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

[toolchain]
channel = "nightly"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/bin/mold",
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[unstable]
codegen-backend = true

[features]
default = ["debugging"]
debugging = ["dep:egui_plot"]
