[package]
name = "include_folder_shared"
version = "0.3.0"
edition = "2021"
description = "Shared code for include_folder and include_folder_macros."
readme = "../README.md"
license = "MIT"
repository = "https://github.com/Joshua861/include_folder"

[dependencies]
globset = "0.4.16"
